version: '3.8'

services:
  app:
    image: php:8.3-apache
    container_name: eventapp_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./config.conf:/etc/apache2/sites-available/config.conf
    ports:
      - "8000:80"
    networks:
      - eventapp_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD  # No password (empty)
    depends_on:
      - db
    command: /bin/bash -c "docker-php-ext-install pdo pdo_mysql && a2enmod rewrite && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: eventapp_db
  environment:
    MYSQL_ROOT_PASSWORD: ""  # No password (empty)
    MYSQL_DATABASE: ${DB_DATABASE}  # Environment variable for database name
    # MYSQL_USER: ${DB_USERNAME}  # Optionally set a regular MySQL user
    MYSQL_PASSWORD: ""  # No password (empty)

    ports:
      - "3307:3306"
    volumes:
      - eventapp_data:/var/lib/mysql
    networks:
      - eventapp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eventapp_pma
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""  # Empty password
       # No password (empty)
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - eventapp_network

networks:
  eventapp_network:
    name: eventapp_network

volumes:
  eventapp_data:
